// Package jsonvalidate is a drop-in fast path for JSON validation: Valid is
// byte-identical to encoding/json.Valid on every input, but accelerates the two
// hottest, embarrassingly-parallel sub-scans with a SIMD kernel generated by
// go-asmgen — scanning a string body for its next significant byte, and
// skipping runs of insignificant whitespace.
//
// # Scope (honest split of SIMD vs scalar)
//
// A full simdjson "stage 1" computes, for a whole block, which structural
// characters lie inside strings. That requires a prefix-XOR over the quote
// bitmask, implemented on amd64 with a carry-less multiply (PCLMULQDQ) that has
// no portable equivalent on the other five 64-bit SIMD targets Go supports
// (arm64, riscv64, loong64, ppc64le, s390x). So a single full-SIMD grammar that
// covers all six arches is not feasible. Instead this package keeps the grammar
// — bracket balancing, number/literal syntax, the exact 10000-deep nesting
// limit, and the encoding/json acceptance rules — in a correct scalar state
// machine, and uses SIMD only for the two scans whose answer is a pure,
// position-independent "find the first byte in (or not in) a small set":
//
//   - scanString: starting just after an opening quote, find the first byte
//     that is '"', '\\' or a control byte (< 0x20). These delimit a JSON string
//     token; everything between is copied verbatim by encoding/json (it does NOT
//     validate UTF-8 inside strings), so a byte-class scan is exactly right.
//   - skipSpace: find the first byte that is not one of the four JSON whitespace
//     bytes (space, tab, newline, carriage return).
//
// Both kernels are shuffle/compare only (nibble-LUT classification via
// PSHUFB/VPERM-class ops); no multiply and no cross-lane carry, so the same
// algorithm ports to all six arches. They are pure accelerators: each returns a
// byte index the scalar machine would have reached anyway, so the verdict can
// never diverge from encoding/json.Valid. The package is therefore always
// correct, and SIMD-accelerated on the fast path; FuzzValid asserts the
// equivalence on arbitrary bytes on every arch.
package jsonvalidate

// maxNestingDepth mirrors encoding/json's scanner: a value nested deeper than
// this many enclosing arrays/objects is rejected. Reaching depth 10000 is
// accepted; opening a 10001st level is not.
const maxNestingDepth = 10000

// Valid reports whether data is a valid JSON encoding. It is a drop-in
// replacement for encoding/json.Valid and returns the same result for every
// input, including malformed UTF-8 inside strings (which, like encoding/json,
// it accepts) and over-deep nesting (which it rejects identically).
func Valid(data []byte) bool {
	d := decoder{data: data}
	d.skipSpace()
	if !d.value() {
		return false
	}
	d.skipSpace()
	// Exactly one top-level value, nothing but whitespace after it.
	return d.pos == len(d.data)
}

// decoder holds the scan cursor over data.
type decoder struct {
	data []byte
	pos  int
}

// skipSpace advances pos past JSON whitespace (space, tab, newline, carriage
// return). skipSpace (the kernel wrapper) does the SIMD bulk and the scalar
// tail, landing pos on the first non-whitespace byte or at end.
func (d *decoder) skipSpace() {
	d.pos = skipSpace(d.data, d.pos)
}

// value parses a single JSON value at pos, returning whether it is well formed
// and advancing pos to just past it. It does not consume trailing whitespace.
func (d *decoder) value() bool {
	if d.pos >= len(d.data) {
		return false
	}
	switch c := d.data[d.pos]; {
	case c == '{':
		return d.object(0)
	case c == '[':
		return d.array(0)
	case c == '"':
		return d.str()
	case c == '-' || (c >= '0' && c <= '9'):
		return d.number()
	case c == 't':
		return d.literal("true")
	case c == 'f':
		return d.literal("false")
	case c == 'n':
		return d.literal("null")
	default:
		return false
	}
}

// valueDepth is value but threads the current nesting depth so arrays and
// objects can enforce maxNestingDepth.
func (d *decoder) valueDepth(depth int) bool {
	if d.pos >= len(d.data) {
		return false
	}
	switch c := d.data[d.pos]; {
	case c == '{':
		return d.object(depth)
	case c == '[':
		return d.array(depth)
	case c == '"':
		return d.str()
	case c == '-' || (c >= '0' && c <= '9'):
		return d.number()
	case c == 't':
		return d.literal("true")
	case c == 'f':
		return d.literal("false")
	case c == 'n':
		return d.literal("null")
	default:
		return false
	}
}

// literal matches the exact bytes of a JSON literal (true/false/null).
func (d *decoder) literal(lit string) bool {
	if d.pos+len(lit) > len(d.data) {
		return false
	}
	for i := 0; i < len(lit); i++ {
		if d.data[d.pos+i] != lit[i] {
			return false
		}
	}
	d.pos += len(lit)
	return true
}

// str parses a JSON string at pos (which must point at the opening quote). The
// SIMD kernel finds the next significant byte ('"', '\\' or a control byte);
// the scalar loop classifies it and handles escapes.
func (d *decoder) str() bool {
	d.pos++ // opening quote
	for {
		d.pos = scanString(d.data, d.pos)
		if d.pos >= len(d.data) {
			return false // unterminated
		}
		switch c := d.data[d.pos]; {
		case c == '"':
			d.pos++
			return true
		case c == '\\':
			if !d.escape() {
				return false
			}
		default:
			// c < 0x20: a raw control byte is not allowed in a JSON string.
			return false
		}
	}
}

// escape consumes a backslash escape sequence; pos points at the backslash.
func (d *decoder) escape() bool {
	d.pos++ // backslash
	if d.pos >= len(d.data) {
		return false
	}
	switch d.data[d.pos] {
	case '"', '\\', '/', 'b', 'f', 'n', 'r', 't':
		d.pos++
		return true
	case 'u':
		d.pos++
		if d.pos+4 > len(d.data) {
			return false
		}
		for i := 0; i < 4; i++ {
			if !isHex(d.data[d.pos+i]) {
				return false
			}
		}
		d.pos += 4
		return true
	default:
		return false
	}
}

func isHex(c byte) bool {
	return (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F')
}

// number parses a JSON number per the grammar
// -?(0|[1-9][0-9]*)(\.[0-9]+)?([eE][+-]?[0-9]+)? with no leading zeros, no
// leading '+', and at least one digit in any fraction/exponent.
func (d *decoder) number() bool {
	n := len(d.data)
	if d.data[d.pos] == '-' {
		d.pos++
		if d.pos >= n {
			return false
		}
	}
	// integer part
	if d.data[d.pos] == '0' {
		d.pos++
	} else if c := d.data[d.pos]; c >= '1' && c <= '9' {
		d.pos++
		for d.pos < n && d.data[d.pos] >= '0' && d.data[d.pos] <= '9' {
			d.pos++
		}
	} else {
		return false
	}
	// fraction
	if d.pos < n && d.data[d.pos] == '.' {
		d.pos++
		if d.pos >= n || d.data[d.pos] < '0' || d.data[d.pos] > '9' {
			return false
		}
		for d.pos < n && d.data[d.pos] >= '0' && d.data[d.pos] <= '9' {
			d.pos++
		}
	}
	// exponent
	if d.pos < n && (d.data[d.pos] == 'e' || d.data[d.pos] == 'E') {
		d.pos++
		if d.pos < n && (d.data[d.pos] == '+' || d.data[d.pos] == '-') {
			d.pos++
		}
		if d.pos >= n || d.data[d.pos] < '0' || d.data[d.pos] > '9' {
			return false
		}
		for d.pos < n && d.data[d.pos] >= '0' && d.data[d.pos] <= '9' {
			d.pos++
		}
	}
	return true
}

// array parses a JSON array at pos (pointing at '['); depth is the count of
// already-open arrays/objects enclosing it.
func (d *decoder) array(depth int) bool {
	if depth+1 > maxNestingDepth {
		return false
	}
	d.pos++ // '['
	d.skipSpace()
	if d.pos < len(d.data) && d.data[d.pos] == ']' {
		d.pos++
		return true
	}
	for {
		d.skipSpace()
		if !d.valueDepth(depth + 1) {
			return false
		}
		d.skipSpace()
		if d.pos >= len(d.data) {
			return false
		}
		switch d.data[d.pos] {
		case ',':
			d.pos++
		case ']':
			d.pos++
			return true
		default:
			return false
		}
	}
}

// object parses a JSON object at pos (pointing at '{'); depth is the count of
// already-open arrays/objects enclosing it.
func (d *decoder) object(depth int) bool {
	if depth+1 > maxNestingDepth {
		return false
	}
	d.pos++ // '{'
	d.skipSpace()
	if d.pos < len(d.data) && d.data[d.pos] == '}' {
		d.pos++
		return true
	}
	for {
		d.skipSpace()
		// key must be a string
		if d.pos >= len(d.data) || d.data[d.pos] != '"' {
			return false
		}
		if !d.str() {
			return false
		}
		d.skipSpace()
		if d.pos >= len(d.data) || d.data[d.pos] != ':' {
			return false
		}
		d.pos++
		d.skipSpace()
		if !d.valueDepth(depth + 1) {
			return false
		}
		d.skipSpace()
		if d.pos >= len(d.data) {
			return false
		}
		switch d.data[d.pos] {
		case ',':
			d.pos++
		case '}':
			d.pos++
			return true
		default:
			return false
		}
	}
}
