//go:build ppc64le

package jsonvalidate

import "golang.org/x/sys/cpu"

// scanStrVSX returns the first index >= off in data whose byte is '"', '\\' or
// < 0x20, over full 16-byte VSX blocks, or the block-aligned end if none.
// skipWsVSX returns the first non-whitespace index, or the block-aligned end.
// The kernels emit ISA-3.0 (POWER9) instructions (LXVB16X, CNTTZD), which raise
// SIGILL on POWER8, so they run only when hasVSX reports POWER9+; on POWER8 the
// scalar scan (scan.go) does all the work — both paths return identical
// results.
// Generated by go-asmgen (scan_ppc64le_gen.go), in scan_ppc64le.s.
func scanStrVSX(data []byte, off int64) int64
func skipWsVSX(data []byte, off int64) int64

// hasVSX gates the generated kernels. They use ISA-3.0 (POWER9) instructions
// (LXVB16X, CNTTZD) that are illegal on POWER8, so the kernels run only on
// POWER9+; otherwise the scalar scan handles everything. It is a var (not a
// const) so the dispatch test can also drive the fallback.
var hasVSX = cpu.PPC64.IsPOWER9

func scanString(data []byte, off int) int {
	if hasVSX && len(data)-off >= 16 {
		off = int(scanStrVSX(data, int64(off)))
	}
	return scanStringScalar(data, off)
}

func skipSpace(data []byte, off int) int {
	if hasVSX && len(data)-off >= 16 {
		off = int(skipWsVSX(data, int64(off)))
	}
	return skipSpaceScalar(data, off)
}
