// Code generated by go-asmgen. DO NOT EDIT.

//go:build ppc64le

#include "textflag.h"

TEXT ·scanStrVSX(SB), NOSPLIT, $0-40
	MOVD data_base+0(FP), R4
	MOVD data_len+8(FP), R5
	MOVD off+24(FP), R7
	MOVD $strLo_p<>+0(SB), R6
	LXVB16X (R0)(R6), VS56
	MOVD $strHi_p<>+0(SB), R6
	LXVB16X (R0)(R6), VS57
	MOVD $c04_p<>+0(SB), R6
	LXVB16X (R0)(R6), VS58
	MOVD $c0F_p<>+0(SB), R6
	LXVB16X (R0)(R6), VS59
loop:
	ADD $16, R7, R8
	CMP R5, R8
	BLT done
	ADD R4, R7, R9
	LXVD2X (R0)(R9), VS32
	VAND V0, V27, V1
	VPERM V24, V24, V1, V2
	VSRB V0, V26, V3
	VPERM V25, V25, V3, V4
	VAND V2, V4, V5
	MFVSRD VS37, R10
	CMP R10, $0
	BNE lo
	VSLDOI $8, V5, V5, V6
	MFVSRD VS38, R10
	CMP R10, $0
	BNE hi
	ADD $16, R7, R7
	BR loop
lo:
	CNTTZD R10, R12
	SRD $3, R12, R12
	ADD R7, R12, R12
	MOVD R12, ret+32(FP)
	RET
hi:
	CNTTZD R10, R12
	SRD $3, R12, R12
	ADD $8, R12, R12
	ADD R7, R12, R12
	MOVD R12, ret+32(FP)
	RET
done:
	MOVD R7, ret+32(FP)
	RET

TEXT ·skipWsVSX(SB), NOSPLIT, $0-40
	MOVD data_base+0(FP), R4
	MOVD data_len+8(FP), R5
	MOVD off+24(FP), R7
	MOVD $wsLo_p<>+0(SB), R6
	LXVB16X (R0)(R6), VS56
	MOVD $wsHi_p<>+0(SB), R6
	LXVB16X (R0)(R6), VS57
	MOVD $c04_p<>+0(SB), R6
	LXVB16X (R0)(R6), VS58
	MOVD $c0F_p<>+0(SB), R6
	LXVB16X (R0)(R6), VS59
loop:
	ADD $16, R7, R8
	CMP R5, R8
	BLT done
	ADD R4, R7, R9
	LXVD2X (R0)(R9), VS32
	VAND V0, V27, V1
	VPERM V24, V24, V1, V2
	VSRB V0, V26, V3
	VPERM V25, V25, V3, V4
	VAND V2, V4, V5
	MFVSRD VS37, R10
	NOR R10, R10, R10
	CMP R10, $0
	BNE lo
	VSLDOI $8, V5, V5, V6
	MFVSRD VS38, R10
	NOR R10, R10, R10
	CMP R10, $0
	BNE hi
	ADD $16, R7, R7
	BR loop
lo:
	CNTTZD R10, R12
	SRD $3, R12, R12
	ADD R7, R12, R12
	MOVD R12, ret+32(FP)
	RET
hi:
	CNTTZD R10, R12
	SRD $3, R12, R12
	ADD $8, R12, R12
	ADD R7, R12, R12
	MOVD R12, ret+32(FP)
	RET
done:
	MOVD R7, ret+32(FP)
	RET

DATA strLo_p<>+0(SB)/1, $0x03
DATA strLo_p<>+1(SB)/1, $0x03
DATA strLo_p<>+2(SB)/1, $0x07
DATA strLo_p<>+3(SB)/1, $0x03
DATA strLo_p<>+4(SB)/1, $0x03
DATA strLo_p<>+5(SB)/1, $0x03
DATA strLo_p<>+6(SB)/1, $0x03
DATA strLo_p<>+7(SB)/1, $0x03
DATA strLo_p<>+8(SB)/1, $0x03
DATA strLo_p<>+9(SB)/1, $0x03
DATA strLo_p<>+10(SB)/1, $0x03
DATA strLo_p<>+11(SB)/1, $0x03
DATA strLo_p<>+12(SB)/1, $0x0b
DATA strLo_p<>+13(SB)/1, $0x03
DATA strLo_p<>+14(SB)/1, $0x03
DATA strLo_p<>+15(SB)/1, $0x03
GLOBL strLo_p<>(SB), RODATA|NOPTR, $16

DATA strHi_p<>+0(SB)/1, $0x01
DATA strHi_p<>+1(SB)/1, $0x02
DATA strHi_p<>+2(SB)/1, $0x04
DATA strHi_p<>+3(SB)/1, $0x00
DATA strHi_p<>+4(SB)/1, $0x00
DATA strHi_p<>+5(SB)/1, $0x08
DATA strHi_p<>+6(SB)/1, $0x00
DATA strHi_p<>+7(SB)/1, $0x00
DATA strHi_p<>+8(SB)/1, $0x00
DATA strHi_p<>+9(SB)/1, $0x00
DATA strHi_p<>+10(SB)/1, $0x00
DATA strHi_p<>+11(SB)/1, $0x00
DATA strHi_p<>+12(SB)/1, $0x00
DATA strHi_p<>+13(SB)/1, $0x00
DATA strHi_p<>+14(SB)/1, $0x00
DATA strHi_p<>+15(SB)/1, $0x00
GLOBL strHi_p<>(SB), RODATA|NOPTR, $16

DATA wsLo_p<>+0(SB)/1, $0x02
DATA wsLo_p<>+1(SB)/1, $0x00
DATA wsLo_p<>+2(SB)/1, $0x00
DATA wsLo_p<>+3(SB)/1, $0x00
DATA wsLo_p<>+4(SB)/1, $0x00
DATA wsLo_p<>+5(SB)/1, $0x00
DATA wsLo_p<>+6(SB)/1, $0x00
DATA wsLo_p<>+7(SB)/1, $0x00
DATA wsLo_p<>+8(SB)/1, $0x00
DATA wsLo_p<>+9(SB)/1, $0x01
DATA wsLo_p<>+10(SB)/1, $0x01
DATA wsLo_p<>+11(SB)/1, $0x00
DATA wsLo_p<>+12(SB)/1, $0x00
DATA wsLo_p<>+13(SB)/1, $0x01
DATA wsLo_p<>+14(SB)/1, $0x00
DATA wsLo_p<>+15(SB)/1, $0x00
GLOBL wsLo_p<>(SB), RODATA|NOPTR, $16

DATA wsHi_p<>+0(SB)/1, $0x01
DATA wsHi_p<>+1(SB)/1, $0x00
DATA wsHi_p<>+2(SB)/1, $0x02
DATA wsHi_p<>+3(SB)/1, $0x00
DATA wsHi_p<>+4(SB)/1, $0x00
DATA wsHi_p<>+5(SB)/1, $0x00
DATA wsHi_p<>+6(SB)/1, $0x00
DATA wsHi_p<>+7(SB)/1, $0x00
DATA wsHi_p<>+8(SB)/1, $0x00
DATA wsHi_p<>+9(SB)/1, $0x00
DATA wsHi_p<>+10(SB)/1, $0x00
DATA wsHi_p<>+11(SB)/1, $0x00
DATA wsHi_p<>+12(SB)/1, $0x00
DATA wsHi_p<>+13(SB)/1, $0x00
DATA wsHi_p<>+14(SB)/1, $0x00
DATA wsHi_p<>+15(SB)/1, $0x00
GLOBL wsHi_p<>(SB), RODATA|NOPTR, $16

DATA c04_p<>+0(SB)/1, $0x04
DATA c04_p<>+1(SB)/1, $0x04
DATA c04_p<>+2(SB)/1, $0x04
DATA c04_p<>+3(SB)/1, $0x04
DATA c04_p<>+4(SB)/1, $0x04
DATA c04_p<>+5(SB)/1, $0x04
DATA c04_p<>+6(SB)/1, $0x04
DATA c04_p<>+7(SB)/1, $0x04
DATA c04_p<>+8(SB)/1, $0x04
DATA c04_p<>+9(SB)/1, $0x04
DATA c04_p<>+10(SB)/1, $0x04
DATA c04_p<>+11(SB)/1, $0x04
DATA c04_p<>+12(SB)/1, $0x04
DATA c04_p<>+13(SB)/1, $0x04
DATA c04_p<>+14(SB)/1, $0x04
DATA c04_p<>+15(SB)/1, $0x04
GLOBL c04_p<>(SB), RODATA|NOPTR, $16

DATA c0F_p<>+0(SB)/1, $0x0f
DATA c0F_p<>+1(SB)/1, $0x0f
DATA c0F_p<>+2(SB)/1, $0x0f
DATA c0F_p<>+3(SB)/1, $0x0f
DATA c0F_p<>+4(SB)/1, $0x0f
DATA c0F_p<>+5(SB)/1, $0x0f
DATA c0F_p<>+6(SB)/1, $0x0f
DATA c0F_p<>+7(SB)/1, $0x0f
DATA c0F_p<>+8(SB)/1, $0x0f
DATA c0F_p<>+9(SB)/1, $0x0f
DATA c0F_p<>+10(SB)/1, $0x0f
DATA c0F_p<>+11(SB)/1, $0x0f
DATA c0F_p<>+12(SB)/1, $0x0f
DATA c0F_p<>+13(SB)/1, $0x0f
DATA c0F_p<>+14(SB)/1, $0x0f
DATA c0F_p<>+15(SB)/1, $0x0f
GLOBL c0F_p<>(SB), RODATA|NOPTR, $16

