// Code generated by go-asmgen. DO NOT EDIT.

//go:build riscv64

#include "textflag.h"

TEXT ·scanStrRVV(SB), NOSPLIT, $0-40
	MOV data_base+0(FP), X5
	MOV data_len+8(FP), X6
	MOV off+24(FP), X7
	VSETVLI $16, E8, M1, TA, MA, X8
	MOV $strLo_r<>+0(SB), X9
	VLE8V (X9), V8
	MOV $strHi_r<>+0(SB), X9
	VLE8V (X9), V9
loop:
	ADD $16, X7, X10
	BLT X6, X10, done
	ADD X5, X7, X11
	VLE8V (X11), V1
	VANDVI $15, V1, V2
	VRGATHERVV V2, V8, V3
	VSRLVI $4, V1, V2
	VANDVI $15, V2, V2
	VRGATHERVV V2, V9, V4
	VANDVV V3, V4, V5
	VMSNEVI $0, V5, V0
	VFIRSTM V0, X12
	BGE X12, X0, found
	ADD $16, X7, X7
	JMP loop
found:
	ADD X7, X12, X12
	MOV X12, ret+32(FP)
	RET
done:
	MOV X7, ret+32(FP)
	RET

TEXT ·skipWsRVV(SB), NOSPLIT, $0-40
	MOV data_base+0(FP), X5
	MOV data_len+8(FP), X6
	MOV off+24(FP), X7
	VSETVLI $16, E8, M1, TA, MA, X8
	MOV $wsLo_r<>+0(SB), X9
	VLE8V (X9), V8
	MOV $wsHi_r<>+0(SB), X9
	VLE8V (X9), V9
loop:
	ADD $16, X7, X10
	BLT X6, X10, done
	ADD X5, X7, X11
	VLE8V (X11), V1
	VANDVI $15, V1, V2
	VRGATHERVV V2, V8, V3
	VSRLVI $4, V1, V2
	VANDVI $15, V2, V2
	VRGATHERVV V2, V9, V4
	VANDVV V3, V4, V5
	VMSEQVI $0, V5, V0
	VFIRSTM V0, X12
	BGE X12, X0, found
	ADD $16, X7, X7
	JMP loop
found:
	ADD X7, X12, X12
	MOV X12, ret+32(FP)
	RET
done:
	MOV X7, ret+32(FP)
	RET

DATA strLo_r<>+0(SB)/1, $0x03
DATA strLo_r<>+1(SB)/1, $0x03
DATA strLo_r<>+2(SB)/1, $0x07
DATA strLo_r<>+3(SB)/1, $0x03
DATA strLo_r<>+4(SB)/1, $0x03
DATA strLo_r<>+5(SB)/1, $0x03
DATA strLo_r<>+6(SB)/1, $0x03
DATA strLo_r<>+7(SB)/1, $0x03
DATA strLo_r<>+8(SB)/1, $0x03
DATA strLo_r<>+9(SB)/1, $0x03
DATA strLo_r<>+10(SB)/1, $0x03
DATA strLo_r<>+11(SB)/1, $0x03
DATA strLo_r<>+12(SB)/1, $0x0b
DATA strLo_r<>+13(SB)/1, $0x03
DATA strLo_r<>+14(SB)/1, $0x03
DATA strLo_r<>+15(SB)/1, $0x03
GLOBL strLo_r<>(SB), RODATA|NOPTR, $16

DATA strHi_r<>+0(SB)/1, $0x01
DATA strHi_r<>+1(SB)/1, $0x02
DATA strHi_r<>+2(SB)/1, $0x04
DATA strHi_r<>+3(SB)/1, $0x00
DATA strHi_r<>+4(SB)/1, $0x00
DATA strHi_r<>+5(SB)/1, $0x08
DATA strHi_r<>+6(SB)/1, $0x00
DATA strHi_r<>+7(SB)/1, $0x00
DATA strHi_r<>+8(SB)/1, $0x00
DATA strHi_r<>+9(SB)/1, $0x00
DATA strHi_r<>+10(SB)/1, $0x00
DATA strHi_r<>+11(SB)/1, $0x00
DATA strHi_r<>+12(SB)/1, $0x00
DATA strHi_r<>+13(SB)/1, $0x00
DATA strHi_r<>+14(SB)/1, $0x00
DATA strHi_r<>+15(SB)/1, $0x00
GLOBL strHi_r<>(SB), RODATA|NOPTR, $16

DATA wsLo_r<>+0(SB)/1, $0x02
DATA wsLo_r<>+1(SB)/1, $0x00
DATA wsLo_r<>+2(SB)/1, $0x00
DATA wsLo_r<>+3(SB)/1, $0x00
DATA wsLo_r<>+4(SB)/1, $0x00
DATA wsLo_r<>+5(SB)/1, $0x00
DATA wsLo_r<>+6(SB)/1, $0x00
DATA wsLo_r<>+7(SB)/1, $0x00
DATA wsLo_r<>+8(SB)/1, $0x00
DATA wsLo_r<>+9(SB)/1, $0x01
DATA wsLo_r<>+10(SB)/1, $0x01
DATA wsLo_r<>+11(SB)/1, $0x00
DATA wsLo_r<>+12(SB)/1, $0x00
DATA wsLo_r<>+13(SB)/1, $0x01
DATA wsLo_r<>+14(SB)/1, $0x00
DATA wsLo_r<>+15(SB)/1, $0x00
GLOBL wsLo_r<>(SB), RODATA|NOPTR, $16

DATA wsHi_r<>+0(SB)/1, $0x01
DATA wsHi_r<>+1(SB)/1, $0x00
DATA wsHi_r<>+2(SB)/1, $0x02
DATA wsHi_r<>+3(SB)/1, $0x00
DATA wsHi_r<>+4(SB)/1, $0x00
DATA wsHi_r<>+5(SB)/1, $0x00
DATA wsHi_r<>+6(SB)/1, $0x00
DATA wsHi_r<>+7(SB)/1, $0x00
DATA wsHi_r<>+8(SB)/1, $0x00
DATA wsHi_r<>+9(SB)/1, $0x00
DATA wsHi_r<>+10(SB)/1, $0x00
DATA wsHi_r<>+11(SB)/1, $0x00
DATA wsHi_r<>+12(SB)/1, $0x00
DATA wsHi_r<>+13(SB)/1, $0x00
DATA wsHi_r<>+14(SB)/1, $0x00
DATA wsHi_r<>+15(SB)/1, $0x00
GLOBL wsHi_r<>(SB), RODATA|NOPTR, $16

