// Code generated by go-asmgen. DO NOT EDIT.

//go:build s390x

#include "textflag.h"

TEXT ·scanStrVX(SB), NOSPLIT, $0-40
	MOVD data_base+0(FP), R2
	MOVD data_len+8(FP), R3
	MOVD off+24(FP), R4
	MOVD $strLo_z<>+0(SB), R5
	VL (R5), V24
	MOVD $strHi_z<>+0(SB), R5
	VL (R5), V25
	VZERO V30
loop:
	ADD $16, R4, R6
	CMPBGT R6, R3, done
	ADD R2, R4, R7
	VL (R7), V0
	VESRLB $4, V0, V1
	VESLB $4, V1, V2
	VSB V2, V0, V3
	VPERM V24, V24, V3, V4
	VPERM V25, V25, V1, V5
	VN V4, V5, V6
	VFENEBS V6, V30, V2
	BVS next
	VLGVB $7, V2, R8
	ADD R4, R8, R8
	MOVD R8, ret+32(FP)
	RET
next:
	ADD $16, R4, R4
	BR loop
done:
	MOVD R4, ret+32(FP)
	RET

TEXT ·skipWsVX(SB), NOSPLIT, $0-40
	MOVD data_base+0(FP), R2
	MOVD data_len+8(FP), R3
	MOVD off+24(FP), R4
	MOVD $wsLo_z<>+0(SB), R5
	VL (R5), V24
	MOVD $wsHi_z<>+0(SB), R5
	VL (R5), V25
	VZERO V30
loop:
	ADD $16, R4, R6
	CMPBGT R6, R3, done
	ADD R2, R4, R7
	VL (R7), V0
	VESRLB $4, V0, V1
	VESLB $4, V1, V2
	VSB V2, V0, V3
	VPERM V24, V24, V3, V4
	VPERM V25, V25, V1, V5
	VN V4, V5, V6
	VCEQB V6, V30, V6
	VFENEBS V6, V30, V2
	BVS next
	VLGVB $7, V2, R8
	ADD R4, R8, R8
	MOVD R8, ret+32(FP)
	RET
next:
	ADD $16, R4, R4
	BR loop
done:
	MOVD R4, ret+32(FP)
	RET

DATA strLo_z<>+0(SB)/1, $0x03
DATA strLo_z<>+1(SB)/1, $0x03
DATA strLo_z<>+2(SB)/1, $0x07
DATA strLo_z<>+3(SB)/1, $0x03
DATA strLo_z<>+4(SB)/1, $0x03
DATA strLo_z<>+5(SB)/1, $0x03
DATA strLo_z<>+6(SB)/1, $0x03
DATA strLo_z<>+7(SB)/1, $0x03
DATA strLo_z<>+8(SB)/1, $0x03
DATA strLo_z<>+9(SB)/1, $0x03
DATA strLo_z<>+10(SB)/1, $0x03
DATA strLo_z<>+11(SB)/1, $0x03
DATA strLo_z<>+12(SB)/1, $0x0b
DATA strLo_z<>+13(SB)/1, $0x03
DATA strLo_z<>+14(SB)/1, $0x03
DATA strLo_z<>+15(SB)/1, $0x03
GLOBL strLo_z<>(SB), RODATA|NOPTR, $16

DATA strHi_z<>+0(SB)/1, $0x01
DATA strHi_z<>+1(SB)/1, $0x02
DATA strHi_z<>+2(SB)/1, $0x04
DATA strHi_z<>+3(SB)/1, $0x00
DATA strHi_z<>+4(SB)/1, $0x00
DATA strHi_z<>+5(SB)/1, $0x08
DATA strHi_z<>+6(SB)/1, $0x00
DATA strHi_z<>+7(SB)/1, $0x00
DATA strHi_z<>+8(SB)/1, $0x00
DATA strHi_z<>+9(SB)/1, $0x00
DATA strHi_z<>+10(SB)/1, $0x00
DATA strHi_z<>+11(SB)/1, $0x00
DATA strHi_z<>+12(SB)/1, $0x00
DATA strHi_z<>+13(SB)/1, $0x00
DATA strHi_z<>+14(SB)/1, $0x00
DATA strHi_z<>+15(SB)/1, $0x00
GLOBL strHi_z<>(SB), RODATA|NOPTR, $16

DATA wsLo_z<>+0(SB)/1, $0x02
DATA wsLo_z<>+1(SB)/1, $0x00
DATA wsLo_z<>+2(SB)/1, $0x00
DATA wsLo_z<>+3(SB)/1, $0x00
DATA wsLo_z<>+4(SB)/1, $0x00
DATA wsLo_z<>+5(SB)/1, $0x00
DATA wsLo_z<>+6(SB)/1, $0x00
DATA wsLo_z<>+7(SB)/1, $0x00
DATA wsLo_z<>+8(SB)/1, $0x00
DATA wsLo_z<>+9(SB)/1, $0x01
DATA wsLo_z<>+10(SB)/1, $0x01
DATA wsLo_z<>+11(SB)/1, $0x00
DATA wsLo_z<>+12(SB)/1, $0x00
DATA wsLo_z<>+13(SB)/1, $0x01
DATA wsLo_z<>+14(SB)/1, $0x00
DATA wsLo_z<>+15(SB)/1, $0x00
GLOBL wsLo_z<>(SB), RODATA|NOPTR, $16

DATA wsHi_z<>+0(SB)/1, $0x01
DATA wsHi_z<>+1(SB)/1, $0x00
DATA wsHi_z<>+2(SB)/1, $0x02
DATA wsHi_z<>+3(SB)/1, $0x00
DATA wsHi_z<>+4(SB)/1, $0x00
DATA wsHi_z<>+5(SB)/1, $0x00
DATA wsHi_z<>+6(SB)/1, $0x00
DATA wsHi_z<>+7(SB)/1, $0x00
DATA wsHi_z<>+8(SB)/1, $0x00
DATA wsHi_z<>+9(SB)/1, $0x00
DATA wsHi_z<>+10(SB)/1, $0x00
DATA wsHi_z<>+11(SB)/1, $0x00
DATA wsHi_z<>+12(SB)/1, $0x00
DATA wsHi_z<>+13(SB)/1, $0x00
DATA wsHi_z<>+14(SB)/1, $0x00
DATA wsHi_z<>+15(SB)/1, $0x00
GLOBL wsHi_z<>(SB), RODATA|NOPTR, $16

