//go:build ppc64le

package jsonvalidate

// scanStrVSX returns the first index >= off in data whose byte is '"', '\\' or
// < 0x20, over full 16-byte VSX blocks, or the block-aligned end if none.
// skipWsVSX returns the first non-whitespace index, or the block-aligned end.
// Generated by go-asmgen (scan_ppc64le_gen.go), in scan_ppc64le.s.
func scanStrVSX(data []byte, off int64) int64
func skipWsVSX(data []byte, off int64) int64

func scanString(data []byte, off int) int {
	if len(data)-off >= 16 {
		off = int(scanStrVSX(data, int64(off)))
	}
	return scanStringScalar(data, off)
}

func skipSpace(data []byte, off int) int {
	if len(data)-off >= 16 {
		off = int(skipWsVSX(data, int64(off)))
	}
	return skipSpaceScalar(data, off)
}
