//go:build amd64

package jsonvalidate

import "golang.org/x/sys/cpu"

// scanStrSSE/scanStrAVX2 return the first index >= off in data whose byte is
// '"', '\\' or < 0x20, searched over full 16-/32-byte blocks; if none match they
// return the block-aligned end of the scanned region. skipWsSSE/skipWsAVX2
// likewise return the first non-whitespace index, or the block-aligned end.
// Generated by go-asmgen (scan_amd64_gen.go), in scan_amd64.s.
func scanStrSSE(data []byte, off int64) int64
func scanStrAVX2(data []byte, off int64) int64
func skipWsSSE(data []byte, off int64) int64
func skipWsAVX2(data []byte, off int64) int64

var hasAVX2 = cpu.X86.HasAVX2

// scanString runs the widest available SIMD kernel over the block-aligned
// region from off, then finishes the sub-stride tail with the scalar reference.
func scanString(data []byte, off int) int {
	if hasAVX2 && len(data)-off >= 32 {
		off = int(scanStrAVX2(data, int64(off)))
	} else if len(data)-off >= 16 {
		off = int(scanStrSSE(data, int64(off)))
	}
	return scanStringScalar(data, off)
}

// skipSpace runs the widest available SIMD kernel then scalar-tails.
func skipSpace(data []byte, off int) int {
	if hasAVX2 && len(data)-off >= 32 {
		off = int(skipWsAVX2(data, int64(off)))
	} else if len(data)-off >= 16 {
		off = int(skipWsSSE(data, int64(off)))
	}
	return skipSpaceScalar(data, off)
}
