// Code generated by go-asmgen. DO NOT EDIT.

//go:build arm64

#include "textflag.h"

TEXT ·scanStrNEON(SB), NOSPLIT, $0-40
	MOVD data_base+0(FP), R0
	MOVD data_len+8(FP), R1
	MOVD off+24(FP), R2
	MOVD $strLo_a<>+0(SB), R3
	VLD1 (R3), [V6.B16]
	MOVD $strHi_a<>+0(SB), R3
	VLD1 (R3), [V7.B16]
	MOVD $c0F_a<>+0(SB), R3
	VLD1 (R3), [V8.B16]
	VEOR V9.B16, V9.B16, V9.B16
loop:
	ADD $16, R2, R4
	CMP R1, R4
	BGT done
	ADD R0, R2, R5
	VLD1 (R5), [V0.B16]
	VAND V8.B16, V0.B16, V1.B16
	VTBL V1.B16, [V6.B16], V2.B16
	VUSHR $4, V0.B16, V1.B16
	VAND V8.B16, V1.B16, V1.B16
	VTBL V1.B16, [V7.B16], V0.B16
	VAND V2.B16, V0.B16, V0.B16
	VMOV V0.D[0], R6
	CBNZ R6, lo_half
	VMOV V0.D[1], R6
	CBNZ R6, hi_half
	ADD $16, R2, R2
	JMP loop
lo_half:
	RBIT R6, R7
	CLZ R7, R7
	LSR $3, R7, R7
	ADD R2, R7, R7
	MOVD R7, ret+32(FP)
	RET
hi_half:
	RBIT R6, R7
	CLZ R7, R7
	LSR $3, R7, R7
	ADD $8, R7, R7
	ADD R2, R7, R7
	MOVD R7, ret+32(FP)
	RET
done:
	MOVD R2, ret+32(FP)
	RET

TEXT ·skipWsNEON(SB), NOSPLIT, $0-40
	MOVD data_base+0(FP), R0
	MOVD data_len+8(FP), R1
	MOVD off+24(FP), R2
	MOVD $wsLo_a<>+0(SB), R3
	VLD1 (R3), [V6.B16]
	MOVD $wsHi_a<>+0(SB), R3
	VLD1 (R3), [V7.B16]
	MOVD $c0F_a<>+0(SB), R3
	VLD1 (R3), [V8.B16]
	VEOR V9.B16, V9.B16, V9.B16
loop:
	ADD $16, R2, R4
	CMP R1, R4
	BGT done
	ADD R0, R2, R5
	VLD1 (R5), [V0.B16]
	VAND V8.B16, V0.B16, V1.B16
	VTBL V1.B16, [V6.B16], V2.B16
	VUSHR $4, V0.B16, V1.B16
	VAND V8.B16, V1.B16, V1.B16
	VTBL V1.B16, [V7.B16], V0.B16
	VAND V2.B16, V0.B16, V0.B16
	VCMEQ V9.B16, V0.B16, V0.B16
	VMOV V0.D[0], R6
	CBNZ R6, lo_half
	VMOV V0.D[1], R6
	CBNZ R6, hi_half
	ADD $16, R2, R2
	JMP loop
lo_half:
	RBIT R6, R7
	CLZ R7, R7
	LSR $3, R7, R7
	ADD R2, R7, R7
	MOVD R7, ret+32(FP)
	RET
hi_half:
	RBIT R6, R7
	CLZ R7, R7
	LSR $3, R7, R7
	ADD $8, R7, R7
	ADD R2, R7, R7
	MOVD R7, ret+32(FP)
	RET
done:
	MOVD R2, ret+32(FP)
	RET

DATA strLo_a<>+0(SB)/1, $0x03
DATA strLo_a<>+1(SB)/1, $0x03
DATA strLo_a<>+2(SB)/1, $0x07
DATA strLo_a<>+3(SB)/1, $0x03
DATA strLo_a<>+4(SB)/1, $0x03
DATA strLo_a<>+5(SB)/1, $0x03
DATA strLo_a<>+6(SB)/1, $0x03
DATA strLo_a<>+7(SB)/1, $0x03
DATA strLo_a<>+8(SB)/1, $0x03
DATA strLo_a<>+9(SB)/1, $0x03
DATA strLo_a<>+10(SB)/1, $0x03
DATA strLo_a<>+11(SB)/1, $0x03
DATA strLo_a<>+12(SB)/1, $0x0b
DATA strLo_a<>+13(SB)/1, $0x03
DATA strLo_a<>+14(SB)/1, $0x03
DATA strLo_a<>+15(SB)/1, $0x03
GLOBL strLo_a<>(SB), RODATA|NOPTR, $16

DATA strHi_a<>+0(SB)/1, $0x01
DATA strHi_a<>+1(SB)/1, $0x02
DATA strHi_a<>+2(SB)/1, $0x04
DATA strHi_a<>+3(SB)/1, $0x00
DATA strHi_a<>+4(SB)/1, $0x00
DATA strHi_a<>+5(SB)/1, $0x08
DATA strHi_a<>+6(SB)/1, $0x00
DATA strHi_a<>+7(SB)/1, $0x00
DATA strHi_a<>+8(SB)/1, $0x00
DATA strHi_a<>+9(SB)/1, $0x00
DATA strHi_a<>+10(SB)/1, $0x00
DATA strHi_a<>+11(SB)/1, $0x00
DATA strHi_a<>+12(SB)/1, $0x00
DATA strHi_a<>+13(SB)/1, $0x00
DATA strHi_a<>+14(SB)/1, $0x00
DATA strHi_a<>+15(SB)/1, $0x00
GLOBL strHi_a<>(SB), RODATA|NOPTR, $16

DATA wsLo_a<>+0(SB)/1, $0x02
DATA wsLo_a<>+1(SB)/1, $0x00
DATA wsLo_a<>+2(SB)/1, $0x00
DATA wsLo_a<>+3(SB)/1, $0x00
DATA wsLo_a<>+4(SB)/1, $0x00
DATA wsLo_a<>+5(SB)/1, $0x00
DATA wsLo_a<>+6(SB)/1, $0x00
DATA wsLo_a<>+7(SB)/1, $0x00
DATA wsLo_a<>+8(SB)/1, $0x00
DATA wsLo_a<>+9(SB)/1, $0x01
DATA wsLo_a<>+10(SB)/1, $0x01
DATA wsLo_a<>+11(SB)/1, $0x00
DATA wsLo_a<>+12(SB)/1, $0x00
DATA wsLo_a<>+13(SB)/1, $0x01
DATA wsLo_a<>+14(SB)/1, $0x00
DATA wsLo_a<>+15(SB)/1, $0x00
GLOBL wsLo_a<>(SB), RODATA|NOPTR, $16

DATA wsHi_a<>+0(SB)/1, $0x01
DATA wsHi_a<>+1(SB)/1, $0x00
DATA wsHi_a<>+2(SB)/1, $0x02
DATA wsHi_a<>+3(SB)/1, $0x00
DATA wsHi_a<>+4(SB)/1, $0x00
DATA wsHi_a<>+5(SB)/1, $0x00
DATA wsHi_a<>+6(SB)/1, $0x00
DATA wsHi_a<>+7(SB)/1, $0x00
DATA wsHi_a<>+8(SB)/1, $0x00
DATA wsHi_a<>+9(SB)/1, $0x00
DATA wsHi_a<>+10(SB)/1, $0x00
DATA wsHi_a<>+11(SB)/1, $0x00
DATA wsHi_a<>+12(SB)/1, $0x00
DATA wsHi_a<>+13(SB)/1, $0x00
DATA wsHi_a<>+14(SB)/1, $0x00
DATA wsHi_a<>+15(SB)/1, $0x00
GLOBL wsHi_a<>(SB), RODATA|NOPTR, $16

DATA c0F_a<>+0(SB)/1, $0x0f
DATA c0F_a<>+1(SB)/1, $0x0f
DATA c0F_a<>+2(SB)/1, $0x0f
DATA c0F_a<>+3(SB)/1, $0x0f
DATA c0F_a<>+4(SB)/1, $0x0f
DATA c0F_a<>+5(SB)/1, $0x0f
DATA c0F_a<>+6(SB)/1, $0x0f
DATA c0F_a<>+7(SB)/1, $0x0f
DATA c0F_a<>+8(SB)/1, $0x0f
DATA c0F_a<>+9(SB)/1, $0x0f
DATA c0F_a<>+10(SB)/1, $0x0f
DATA c0F_a<>+11(SB)/1, $0x0f
DATA c0F_a<>+12(SB)/1, $0x0f
DATA c0F_a<>+13(SB)/1, $0x0f
DATA c0F_a<>+14(SB)/1, $0x0f
DATA c0F_a<>+15(SB)/1, $0x0f
GLOBL c0F_a<>(SB), RODATA|NOPTR, $16

