// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·scanStrSSE(SB), NOSPLIT, $0-40
	MOVQ data_base+0(FP), SI
	MOVQ data_len+8(FP), DX
	MOVQ off+24(FP), AX
	MOVOU strLo<>+0(SB), X3
	MOVOU strHi<>+0(SB), X4
	MOVOU c0F<>+0(SB), X5
loop:
	MOVQ AX, R8
	ADDQ $16, R8
	CMPQ R8, DX
	JGT done
	MOVOU (SI)(AX*1), X0
	MOVO X0, X1
	PAND X5, X1
	MOVO X3, X2
	PSHUFB X1, X2
	MOVO X0, X1
	PSRLW $4, X1
	PAND X5, X1
	MOVO X4, X0
	PSHUFB X1, X0
	PAND X2, X0
	PXOR X1, X1
	PCMPEQB X1, X0
	PMOVMSKB X0, R9
	NOTL R9
	ANDL $0xFFFF, R9
	TESTL R9, R9
	JZ next
	BSFL R9, R9
	ADDQ R9, AX
	MOVQ AX, ret+32(FP)
	RET
next:
	ADDQ $16, AX
	JMP loop
done:
	MOVQ AX, ret+32(FP)
	RET

TEXT ·skipWsSSE(SB), NOSPLIT, $0-40
	MOVQ data_base+0(FP), SI
	MOVQ data_len+8(FP), DX
	MOVQ off+24(FP), AX
	MOVOU wsLo<>+0(SB), X3
	MOVOU wsHi<>+0(SB), X4
	MOVOU c0F<>+0(SB), X5
loop:
	MOVQ AX, R8
	ADDQ $16, R8
	CMPQ R8, DX
	JGT done
	MOVOU (SI)(AX*1), X0
	MOVO X0, X1
	PAND X5, X1
	MOVO X3, X2
	PSHUFB X1, X2
	MOVO X0, X1
	PSRLW $4, X1
	PAND X5, X1
	MOVO X4, X0
	PSHUFB X1, X0
	PAND X2, X0
	PXOR X1, X1
	PCMPEQB X1, X0
	PMOVMSKB X0, R9
	ANDL $0xFFFF, R9
	TESTL R9, R9
	JZ next
	BSFL R9, R9
	ADDQ R9, AX
	MOVQ AX, ret+32(FP)
	RET
next:
	ADDQ $16, AX
	JMP loop
done:
	MOVQ AX, ret+32(FP)
	RET

TEXT ·scanStrAVX2(SB), NOSPLIT, $0-40
	MOVQ data_base+0(FP), SI
	MOVQ data_len+8(FP), DX
	MOVQ off+24(FP), AX
	VMOVDQU strLoB<>+0(SB), Y3
	VMOVDQU strHiB<>+0(SB), Y4
	VMOVDQU c0Fb<>+0(SB), Y5
	VPXOR Y6, Y6, Y6
loop:
	MOVQ AX, R8
	ADDQ $32, R8
	CMPQ R8, DX
	JGT done
	VMOVDQU (SI)(AX*1), Y0
	VPAND Y5, Y0, Y1
	VPSHUFB Y1, Y3, Y2
	VPSRLW $4, Y0, Y1
	VPAND Y5, Y1, Y1
	VPSHUFB Y1, Y4, Y0
	VPAND Y2, Y0, Y0
	VPCMPEQB Y6, Y0, Y0
	VPMOVMSKB Y0, R9
	NOTL R9
	TESTL R9, R9
	JZ next
	BSFL R9, R9
	ADDQ R9, AX
	VZEROUPPER
	MOVQ AX, ret+32(FP)
	RET
next:
	ADDQ $32, AX
	JMP loop
done:
	VZEROUPPER
	MOVQ AX, ret+32(FP)
	RET

TEXT ·skipWsAVX2(SB), NOSPLIT, $0-40
	MOVQ data_base+0(FP), SI
	MOVQ data_len+8(FP), DX
	MOVQ off+24(FP), AX
	VMOVDQU wsLoB<>+0(SB), Y3
	VMOVDQU wsHiB<>+0(SB), Y4
	VMOVDQU c0Fb<>+0(SB), Y5
	VPXOR Y6, Y6, Y6
loop:
	MOVQ AX, R8
	ADDQ $32, R8
	CMPQ R8, DX
	JGT done
	VMOVDQU (SI)(AX*1), Y0
	VPAND Y5, Y0, Y1
	VPSHUFB Y1, Y3, Y2
	VPSRLW $4, Y0, Y1
	VPAND Y5, Y1, Y1
	VPSHUFB Y1, Y4, Y0
	VPAND Y2, Y0, Y0
	VPCMPEQB Y6, Y0, Y0
	VPMOVMSKB Y0, R9
	TESTL R9, R9
	JZ next
	BSFL R9, R9
	ADDQ R9, AX
	VZEROUPPER
	MOVQ AX, ret+32(FP)
	RET
next:
	ADDQ $32, AX
	JMP loop
done:
	VZEROUPPER
	MOVQ AX, ret+32(FP)
	RET

DATA strLo<>+0(SB)/1, $0x03
DATA strLo<>+1(SB)/1, $0x03
DATA strLo<>+2(SB)/1, $0x07
DATA strLo<>+3(SB)/1, $0x03
DATA strLo<>+4(SB)/1, $0x03
DATA strLo<>+5(SB)/1, $0x03
DATA strLo<>+6(SB)/1, $0x03
DATA strLo<>+7(SB)/1, $0x03
DATA strLo<>+8(SB)/1, $0x03
DATA strLo<>+9(SB)/1, $0x03
DATA strLo<>+10(SB)/1, $0x03
DATA strLo<>+11(SB)/1, $0x03
DATA strLo<>+12(SB)/1, $0x0b
DATA strLo<>+13(SB)/1, $0x03
DATA strLo<>+14(SB)/1, $0x03
DATA strLo<>+15(SB)/1, $0x03
GLOBL strLo<>(SB), RODATA|NOPTR, $16

DATA strHi<>+0(SB)/1, $0x01
DATA strHi<>+1(SB)/1, $0x02
DATA strHi<>+2(SB)/1, $0x04
DATA strHi<>+3(SB)/1, $0x00
DATA strHi<>+4(SB)/1, $0x00
DATA strHi<>+5(SB)/1, $0x08
DATA strHi<>+6(SB)/1, $0x00
DATA strHi<>+7(SB)/1, $0x00
DATA strHi<>+8(SB)/1, $0x00
DATA strHi<>+9(SB)/1, $0x00
DATA strHi<>+10(SB)/1, $0x00
DATA strHi<>+11(SB)/1, $0x00
DATA strHi<>+12(SB)/1, $0x00
DATA strHi<>+13(SB)/1, $0x00
DATA strHi<>+14(SB)/1, $0x00
DATA strHi<>+15(SB)/1, $0x00
GLOBL strHi<>(SB), RODATA|NOPTR, $16

DATA wsLo<>+0(SB)/1, $0x02
DATA wsLo<>+1(SB)/1, $0x00
DATA wsLo<>+2(SB)/1, $0x00
DATA wsLo<>+3(SB)/1, $0x00
DATA wsLo<>+4(SB)/1, $0x00
DATA wsLo<>+5(SB)/1, $0x00
DATA wsLo<>+6(SB)/1, $0x00
DATA wsLo<>+7(SB)/1, $0x00
DATA wsLo<>+8(SB)/1, $0x00
DATA wsLo<>+9(SB)/1, $0x01
DATA wsLo<>+10(SB)/1, $0x01
DATA wsLo<>+11(SB)/1, $0x00
DATA wsLo<>+12(SB)/1, $0x00
DATA wsLo<>+13(SB)/1, $0x01
DATA wsLo<>+14(SB)/1, $0x00
DATA wsLo<>+15(SB)/1, $0x00
GLOBL wsLo<>(SB), RODATA|NOPTR, $16

DATA wsHi<>+0(SB)/1, $0x01
DATA wsHi<>+1(SB)/1, $0x00
DATA wsHi<>+2(SB)/1, $0x02
DATA wsHi<>+3(SB)/1, $0x00
DATA wsHi<>+4(SB)/1, $0x00
DATA wsHi<>+5(SB)/1, $0x00
DATA wsHi<>+6(SB)/1, $0x00
DATA wsHi<>+7(SB)/1, $0x00
DATA wsHi<>+8(SB)/1, $0x00
DATA wsHi<>+9(SB)/1, $0x00
DATA wsHi<>+10(SB)/1, $0x00
DATA wsHi<>+11(SB)/1, $0x00
DATA wsHi<>+12(SB)/1, $0x00
DATA wsHi<>+13(SB)/1, $0x00
DATA wsHi<>+14(SB)/1, $0x00
DATA wsHi<>+15(SB)/1, $0x00
GLOBL wsHi<>(SB), RODATA|NOPTR, $16

DATA c0F<>+0(SB)/1, $0x0f
DATA c0F<>+1(SB)/1, $0x0f
DATA c0F<>+2(SB)/1, $0x0f
DATA c0F<>+3(SB)/1, $0x0f
DATA c0F<>+4(SB)/1, $0x0f
DATA c0F<>+5(SB)/1, $0x0f
DATA c0F<>+6(SB)/1, $0x0f
DATA c0F<>+7(SB)/1, $0x0f
DATA c0F<>+8(SB)/1, $0x0f
DATA c0F<>+9(SB)/1, $0x0f
DATA c0F<>+10(SB)/1, $0x0f
DATA c0F<>+11(SB)/1, $0x0f
DATA c0F<>+12(SB)/1, $0x0f
DATA c0F<>+13(SB)/1, $0x0f
DATA c0F<>+14(SB)/1, $0x0f
DATA c0F<>+15(SB)/1, $0x0f
GLOBL c0F<>(SB), RODATA|NOPTR, $16

DATA strLoB<>+0(SB)/1, $0x03
DATA strLoB<>+1(SB)/1, $0x03
DATA strLoB<>+2(SB)/1, $0x07
DATA strLoB<>+3(SB)/1, $0x03
DATA strLoB<>+4(SB)/1, $0x03
DATA strLoB<>+5(SB)/1, $0x03
DATA strLoB<>+6(SB)/1, $0x03
DATA strLoB<>+7(SB)/1, $0x03
DATA strLoB<>+8(SB)/1, $0x03
DATA strLoB<>+9(SB)/1, $0x03
DATA strLoB<>+10(SB)/1, $0x03
DATA strLoB<>+11(SB)/1, $0x03
DATA strLoB<>+12(SB)/1, $0x0b
DATA strLoB<>+13(SB)/1, $0x03
DATA strLoB<>+14(SB)/1, $0x03
DATA strLoB<>+15(SB)/1, $0x03
DATA strLoB<>+16(SB)/1, $0x03
DATA strLoB<>+17(SB)/1, $0x03
DATA strLoB<>+18(SB)/1, $0x07
DATA strLoB<>+19(SB)/1, $0x03
DATA strLoB<>+20(SB)/1, $0x03
DATA strLoB<>+21(SB)/1, $0x03
DATA strLoB<>+22(SB)/1, $0x03
DATA strLoB<>+23(SB)/1, $0x03
DATA strLoB<>+24(SB)/1, $0x03
DATA strLoB<>+25(SB)/1, $0x03
DATA strLoB<>+26(SB)/1, $0x03
DATA strLoB<>+27(SB)/1, $0x03
DATA strLoB<>+28(SB)/1, $0x0b
DATA strLoB<>+29(SB)/1, $0x03
DATA strLoB<>+30(SB)/1, $0x03
DATA strLoB<>+31(SB)/1, $0x03
GLOBL strLoB<>(SB), RODATA|NOPTR, $32

DATA strHiB<>+0(SB)/1, $0x01
DATA strHiB<>+1(SB)/1, $0x02
DATA strHiB<>+2(SB)/1, $0x04
DATA strHiB<>+3(SB)/1, $0x00
DATA strHiB<>+4(SB)/1, $0x00
DATA strHiB<>+5(SB)/1, $0x08
DATA strHiB<>+6(SB)/1, $0x00
DATA strHiB<>+7(SB)/1, $0x00
DATA strHiB<>+8(SB)/1, $0x00
DATA strHiB<>+9(SB)/1, $0x00
DATA strHiB<>+10(SB)/1, $0x00
DATA strHiB<>+11(SB)/1, $0x00
DATA strHiB<>+12(SB)/1, $0x00
DATA strHiB<>+13(SB)/1, $0x00
DATA strHiB<>+14(SB)/1, $0x00
DATA strHiB<>+15(SB)/1, $0x00
DATA strHiB<>+16(SB)/1, $0x01
DATA strHiB<>+17(SB)/1, $0x02
DATA strHiB<>+18(SB)/1, $0x04
DATA strHiB<>+19(SB)/1, $0x00
DATA strHiB<>+20(SB)/1, $0x00
DATA strHiB<>+21(SB)/1, $0x08
DATA strHiB<>+22(SB)/1, $0x00
DATA strHiB<>+23(SB)/1, $0x00
DATA strHiB<>+24(SB)/1, $0x00
DATA strHiB<>+25(SB)/1, $0x00
DATA strHiB<>+26(SB)/1, $0x00
DATA strHiB<>+27(SB)/1, $0x00
DATA strHiB<>+28(SB)/1, $0x00
DATA strHiB<>+29(SB)/1, $0x00
DATA strHiB<>+30(SB)/1, $0x00
DATA strHiB<>+31(SB)/1, $0x00
GLOBL strHiB<>(SB), RODATA|NOPTR, $32

DATA wsLoB<>+0(SB)/1, $0x02
DATA wsLoB<>+1(SB)/1, $0x00
DATA wsLoB<>+2(SB)/1, $0x00
DATA wsLoB<>+3(SB)/1, $0x00
DATA wsLoB<>+4(SB)/1, $0x00
DATA wsLoB<>+5(SB)/1, $0x00
DATA wsLoB<>+6(SB)/1, $0x00
DATA wsLoB<>+7(SB)/1, $0x00
DATA wsLoB<>+8(SB)/1, $0x00
DATA wsLoB<>+9(SB)/1, $0x01
DATA wsLoB<>+10(SB)/1, $0x01
DATA wsLoB<>+11(SB)/1, $0x00
DATA wsLoB<>+12(SB)/1, $0x00
DATA wsLoB<>+13(SB)/1, $0x01
DATA wsLoB<>+14(SB)/1, $0x00
DATA wsLoB<>+15(SB)/1, $0x00
DATA wsLoB<>+16(SB)/1, $0x02
DATA wsLoB<>+17(SB)/1, $0x00
DATA wsLoB<>+18(SB)/1, $0x00
DATA wsLoB<>+19(SB)/1, $0x00
DATA wsLoB<>+20(SB)/1, $0x00
DATA wsLoB<>+21(SB)/1, $0x00
DATA wsLoB<>+22(SB)/1, $0x00
DATA wsLoB<>+23(SB)/1, $0x00
DATA wsLoB<>+24(SB)/1, $0x00
DATA wsLoB<>+25(SB)/1, $0x01
DATA wsLoB<>+26(SB)/1, $0x01
DATA wsLoB<>+27(SB)/1, $0x00
DATA wsLoB<>+28(SB)/1, $0x00
DATA wsLoB<>+29(SB)/1, $0x01
DATA wsLoB<>+30(SB)/1, $0x00
DATA wsLoB<>+31(SB)/1, $0x00
GLOBL wsLoB<>(SB), RODATA|NOPTR, $32

DATA wsHiB<>+0(SB)/1, $0x01
DATA wsHiB<>+1(SB)/1, $0x00
DATA wsHiB<>+2(SB)/1, $0x02
DATA wsHiB<>+3(SB)/1, $0x00
DATA wsHiB<>+4(SB)/1, $0x00
DATA wsHiB<>+5(SB)/1, $0x00
DATA wsHiB<>+6(SB)/1, $0x00
DATA wsHiB<>+7(SB)/1, $0x00
DATA wsHiB<>+8(SB)/1, $0x00
DATA wsHiB<>+9(SB)/1, $0x00
DATA wsHiB<>+10(SB)/1, $0x00
DATA wsHiB<>+11(SB)/1, $0x00
DATA wsHiB<>+12(SB)/1, $0x00
DATA wsHiB<>+13(SB)/1, $0x00
DATA wsHiB<>+14(SB)/1, $0x00
DATA wsHiB<>+15(SB)/1, $0x00
DATA wsHiB<>+16(SB)/1, $0x01
DATA wsHiB<>+17(SB)/1, $0x00
DATA wsHiB<>+18(SB)/1, $0x02
DATA wsHiB<>+19(SB)/1, $0x00
DATA wsHiB<>+20(SB)/1, $0x00
DATA wsHiB<>+21(SB)/1, $0x00
DATA wsHiB<>+22(SB)/1, $0x00
DATA wsHiB<>+23(SB)/1, $0x00
DATA wsHiB<>+24(SB)/1, $0x00
DATA wsHiB<>+25(SB)/1, $0x00
DATA wsHiB<>+26(SB)/1, $0x00
DATA wsHiB<>+27(SB)/1, $0x00
DATA wsHiB<>+28(SB)/1, $0x00
DATA wsHiB<>+29(SB)/1, $0x00
DATA wsHiB<>+30(SB)/1, $0x00
DATA wsHiB<>+31(SB)/1, $0x00
GLOBL wsHiB<>(SB), RODATA|NOPTR, $32

DATA c0Fb<>+0(SB)/1, $0x0f
DATA c0Fb<>+1(SB)/1, $0x0f
DATA c0Fb<>+2(SB)/1, $0x0f
DATA c0Fb<>+3(SB)/1, $0x0f
DATA c0Fb<>+4(SB)/1, $0x0f
DATA c0Fb<>+5(SB)/1, $0x0f
DATA c0Fb<>+6(SB)/1, $0x0f
DATA c0Fb<>+7(SB)/1, $0x0f
DATA c0Fb<>+8(SB)/1, $0x0f
DATA c0Fb<>+9(SB)/1, $0x0f
DATA c0Fb<>+10(SB)/1, $0x0f
DATA c0Fb<>+11(SB)/1, $0x0f
DATA c0Fb<>+12(SB)/1, $0x0f
DATA c0Fb<>+13(SB)/1, $0x0f
DATA c0Fb<>+14(SB)/1, $0x0f
DATA c0Fb<>+15(SB)/1, $0x0f
DATA c0Fb<>+16(SB)/1, $0x0f
DATA c0Fb<>+17(SB)/1, $0x0f
DATA c0Fb<>+18(SB)/1, $0x0f
DATA c0Fb<>+19(SB)/1, $0x0f
DATA c0Fb<>+20(SB)/1, $0x0f
DATA c0Fb<>+21(SB)/1, $0x0f
DATA c0Fb<>+22(SB)/1, $0x0f
DATA c0Fb<>+23(SB)/1, $0x0f
DATA c0Fb<>+24(SB)/1, $0x0f
DATA c0Fb<>+25(SB)/1, $0x0f
DATA c0Fb<>+26(SB)/1, $0x0f
DATA c0Fb<>+27(SB)/1, $0x0f
DATA c0Fb<>+28(SB)/1, $0x0f
DATA c0Fb<>+29(SB)/1, $0x0f
DATA c0Fb<>+30(SB)/1, $0x0f
DATA c0Fb<>+31(SB)/1, $0x0f
GLOBL c0Fb<>(SB), RODATA|NOPTR, $32

