//go:build riscv64

package jsonvalidate

// scanStrRVV returns the first index >= off in data whose byte is '"', '\\' or
// < 0x20, over full 16-byte RVV blocks, or the block-aligned end if none.
// skipWsRVV returns the first non-whitespace index, or the block-aligned end.
// Generated by go-asmgen (scan_riscv64_gen.go), in scan_riscv64.s.
func scanStrRVV(data []byte, off int64) int64
func skipWsRVV(data []byte, off int64) int64

func scanString(data []byte, off int) int {
	if len(data)-off >= 16 {
		off = int(scanStrRVV(data, int64(off)))
	}
	return scanStringScalar(data, off)
}

func skipSpace(data []byte, off int) int {
	if len(data)-off >= 16 {
		off = int(skipWsRVV(data, int64(off)))
	}
	return skipSpaceScalar(data, off)
}
