//go:build loong64

package jsonvalidate

// scanStrLSX returns the first index >= off in data whose byte is '"', '\\' or
// < 0x20, over full 16-byte LSX blocks, or the block-aligned end if none.
// skipWsLSX returns the first non-whitespace index, or the block-aligned end.
// Generated by go-asmgen (scan_loong64_gen.go), in scan_loong64.s.
func scanStrLSX(data []byte, off int64) int64
func skipWsLSX(data []byte, off int64) int64

func scanString(data []byte, off int) int {
	if len(data)-off >= 16 {
		off = int(scanStrLSX(data, int64(off)))
	}
	return scanStringScalar(data, off)
}

func skipSpace(data []byte, off int) int {
	if len(data)-off >= 16 {
		off = int(skipWsLSX(data, int64(off)))
	}
	return skipSpaceScalar(data, off)
}
