//go:build s390x

package jsonvalidate

// scanStrVX returns the first index >= off in data whose byte is '"', '\\' or
// < 0x20, over full 16-byte vector blocks, or the block-aligned end if none.
// skipWsVX returns the first non-whitespace index, or the block-aligned end.
// Generated by go-asmgen (scan_s390x_gen.go), in scan_s390x.s.
func scanStrVX(data []byte, off int64) int64
func skipWsVX(data []byte, off int64) int64

func scanString(data []byte, off int) int {
	if len(data)-off >= 16 {
		off = int(scanStrVX(data, int64(off)))
	}
	return scanStringScalar(data, off)
}

func skipSpace(data []byte, off int) int {
	if len(data)-off >= 16 {
		off = int(skipWsVX(data, int64(off)))
	}
	return skipSpaceScalar(data, off)
}
