//go:build s390x

package jsonvalidate

// scanStrVX returns the first index >= off in data whose byte is '"', '\\' or
// < 0x20, over full 16-byte vector blocks, or the block-aligned end if none.
// Generated by go-asmgen (scan_s390x_gen.go), in scan_s390x.s.
func scanStrVX(data []byte, off int64) int64

// scanString keeps the SIMD string-body scan on s390x: measured on real IBM z15
// (go1.26.4, count=6) it validates the string-heavy document ~3.3x faster than
// the scalar reference, so the vector kernel is the s390x fast path here.
func scanString(data []byte, off int) int {
	if len(data)-off >= 16 {
		off = int(scanStrVX(data, int64(off)))
	}
	return scanStringScalar(data, off)
}

// skipSpace deliberately does NOT use a vector kernel on s390x. Measured on real
// IBM z15 (go1.26.4, count=6), the vector whitespace scan is a net loss versus
// the scalar reference on the only two inputs that exercise it: 0.74x on the
// whitespace-heavy document and 0.77x on the number-heavy one (JSON numbers are
// separated by short whitespace/comma runs, so the per-block vector setup never
// amortises). The scalar skip is at/above parity there, so s390x routes
// whitespace skipping to it and drops the skipWsVX kernel. This mirrors the
// s390x scalar carve-outs already shipped in go-simd/floats (Dot) and
// go-simd/utf8 (ValidASCII); no other arch is affected.
func skipSpace(data []byte, off int) int {
	return skipSpaceScalar(data, off)
}
