//go:build arm64

package jsonvalidate

// scanStrNEON returns the first index >= off in data whose byte is '"', '\\' or
// < 0x20, searched over full 16-byte NEON blocks; if none match it returns the
// block-aligned end of the scanned region. skipWsNEON likewise returns the first
// non-whitespace index, or the block-aligned end. Generated by go-asmgen
// (scan_arm64_gen.go), in scan_arm64.s.
func scanStrNEON(data []byte, off int64) int64
func skipWsNEON(data []byte, off int64) int64

// scanString runs the NEON kernel over the block-aligned region from off, then
// finishes the sub-stride tail with the scalar reference.
func scanString(data []byte, off int) int {
	if len(data)-off >= 16 {
		off = int(scanStrNEON(data, int64(off)))
	}
	return scanStringScalar(data, off)
}

// skipSpace runs the NEON kernel then scalar-tails.
func skipSpace(data []byte, off int) int {
	if len(data)-off >= 16 {
		off = int(skipWsNEON(data, int64(off)))
	}
	return skipSpaceScalar(data, off)
}
