// Code generated by go-asmgen. DO NOT EDIT.

//go:build loong64

#include "textflag.h"

TEXT ·scanStrLSX(SB), NOSPLIT, $0-40
	MOVV data_base+0(FP), R4
	MOVV data_len+8(FP), R5
	MOVV off+24(FP), R6
	MOVV $strLo_l<>+0(SB), R7
	VMOVQ (R7), V6
	MOVV $strHi_l<>+0(SB), R7
	VMOVQ (R7), V7
	VXORV V8, V8, V8
loop:
	ADDV $16, R6, R8
	BLT R5, R8, done
	ADDV R4, R6, R9
	VMOVQ (R9), V0
	VANDB $15, V0, V1
	VSHUFB V6, V6, V1, V2
	VSRLB $4, V0, V1
	VANDB $15, V1, V1
	VSHUFB V7, V7, V1, V3
	VANDV V2, V3, V0
	VMOVQ V0.V[0], R10
	BNE R10, R0, lo_half
	VMOVQ V0.V[1], R10
	BNE R10, R0, hi_half
	ADDV $16, R6, R6
	JMP loop
lo_half:
	CTZV R10, R11
	SRLV $3, R11, R11
	ADDV R6, R11, R11
	MOVV R11, ret+32(FP)
	RET
hi_half:
	CTZV R10, R11
	SRLV $3, R11, R11
	ADDV $8, R11, R11
	ADDV R6, R11, R11
	MOVV R11, ret+32(FP)
	RET
done:
	MOVV R6, ret+32(FP)
	RET

TEXT ·skipWsLSX(SB), NOSPLIT, $0-40
	MOVV data_base+0(FP), R4
	MOVV data_len+8(FP), R5
	MOVV off+24(FP), R6
	MOVV $wsLo_l<>+0(SB), R7
	VMOVQ (R7), V6
	MOVV $wsHi_l<>+0(SB), R7
	VMOVQ (R7), V7
	VXORV V8, V8, V8
loop:
	ADDV $16, R6, R8
	BLT R5, R8, done
	ADDV R4, R6, R9
	VMOVQ (R9), V0
	VANDB $15, V0, V1
	VSHUFB V6, V6, V1, V2
	VSRLB $4, V0, V1
	VANDB $15, V1, V1
	VSHUFB V7, V7, V1, V3
	VANDV V2, V3, V0
	VSEQB V8, V0, V0
	VMOVQ V0.V[0], R10
	BNE R10, R0, lo_half
	VMOVQ V0.V[1], R10
	BNE R10, R0, hi_half
	ADDV $16, R6, R6
	JMP loop
lo_half:
	CTZV R10, R11
	SRLV $3, R11, R11
	ADDV R6, R11, R11
	MOVV R11, ret+32(FP)
	RET
hi_half:
	CTZV R10, R11
	SRLV $3, R11, R11
	ADDV $8, R11, R11
	ADDV R6, R11, R11
	MOVV R11, ret+32(FP)
	RET
done:
	MOVV R6, ret+32(FP)
	RET

DATA strLo_l<>+0(SB)/1, $0x03
DATA strLo_l<>+1(SB)/1, $0x03
DATA strLo_l<>+2(SB)/1, $0x07
DATA strLo_l<>+3(SB)/1, $0x03
DATA strLo_l<>+4(SB)/1, $0x03
DATA strLo_l<>+5(SB)/1, $0x03
DATA strLo_l<>+6(SB)/1, $0x03
DATA strLo_l<>+7(SB)/1, $0x03
DATA strLo_l<>+8(SB)/1, $0x03
DATA strLo_l<>+9(SB)/1, $0x03
DATA strLo_l<>+10(SB)/1, $0x03
DATA strLo_l<>+11(SB)/1, $0x03
DATA strLo_l<>+12(SB)/1, $0x0b
DATA strLo_l<>+13(SB)/1, $0x03
DATA strLo_l<>+14(SB)/1, $0x03
DATA strLo_l<>+15(SB)/1, $0x03
GLOBL strLo_l<>(SB), RODATA|NOPTR, $16

DATA strHi_l<>+0(SB)/1, $0x01
DATA strHi_l<>+1(SB)/1, $0x02
DATA strHi_l<>+2(SB)/1, $0x04
DATA strHi_l<>+3(SB)/1, $0x00
DATA strHi_l<>+4(SB)/1, $0x00
DATA strHi_l<>+5(SB)/1, $0x08
DATA strHi_l<>+6(SB)/1, $0x00
DATA strHi_l<>+7(SB)/1, $0x00
DATA strHi_l<>+8(SB)/1, $0x00
DATA strHi_l<>+9(SB)/1, $0x00
DATA strHi_l<>+10(SB)/1, $0x00
DATA strHi_l<>+11(SB)/1, $0x00
DATA strHi_l<>+12(SB)/1, $0x00
DATA strHi_l<>+13(SB)/1, $0x00
DATA strHi_l<>+14(SB)/1, $0x00
DATA strHi_l<>+15(SB)/1, $0x00
GLOBL strHi_l<>(SB), RODATA|NOPTR, $16

DATA wsLo_l<>+0(SB)/1, $0x02
DATA wsLo_l<>+1(SB)/1, $0x00
DATA wsLo_l<>+2(SB)/1, $0x00
DATA wsLo_l<>+3(SB)/1, $0x00
DATA wsLo_l<>+4(SB)/1, $0x00
DATA wsLo_l<>+5(SB)/1, $0x00
DATA wsLo_l<>+6(SB)/1, $0x00
DATA wsLo_l<>+7(SB)/1, $0x00
DATA wsLo_l<>+8(SB)/1, $0x00
DATA wsLo_l<>+9(SB)/1, $0x01
DATA wsLo_l<>+10(SB)/1, $0x01
DATA wsLo_l<>+11(SB)/1, $0x00
DATA wsLo_l<>+12(SB)/1, $0x00
DATA wsLo_l<>+13(SB)/1, $0x01
DATA wsLo_l<>+14(SB)/1, $0x00
DATA wsLo_l<>+15(SB)/1, $0x00
GLOBL wsLo_l<>(SB), RODATA|NOPTR, $16

DATA wsHi_l<>+0(SB)/1, $0x01
DATA wsHi_l<>+1(SB)/1, $0x00
DATA wsHi_l<>+2(SB)/1, $0x02
DATA wsHi_l<>+3(SB)/1, $0x00
DATA wsHi_l<>+4(SB)/1, $0x00
DATA wsHi_l<>+5(SB)/1, $0x00
DATA wsHi_l<>+6(SB)/1, $0x00
DATA wsHi_l<>+7(SB)/1, $0x00
DATA wsHi_l<>+8(SB)/1, $0x00
DATA wsHi_l<>+9(SB)/1, $0x00
DATA wsHi_l<>+10(SB)/1, $0x00
DATA wsHi_l<>+11(SB)/1, $0x00
DATA wsHi_l<>+12(SB)/1, $0x00
DATA wsHi_l<>+13(SB)/1, $0x00
DATA wsHi_l<>+14(SB)/1, $0x00
DATA wsHi_l<>+15(SB)/1, $0x00
GLOBL wsHi_l<>(SB), RODATA|NOPTR, $16

